[gcp_service_account]
type = "service_account"
project_id = "weatherdiaries"
private_key_id = "1a54a5ed4e1856474c4876079d3dd183f0213185"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDM1F0hWhKCE2Vy
aPKUtgbwlOa3ES0p85OCqKkLpul7I9TpprFzoO50dL1a0YRIpNLXMp+Y0ztDkird
Te3wrYBufd6EpDIHpz23A8bQI/6s3KHgO/AQRWL6+DPNKPG8KGVfFHWXjZS0hrOc
IUYupDbLZ8JgJPt/ptyGlB/h7vCQIL70pMUkWjJVI7vnv0BQxtUgaSWT9dYAKF5Q
Tj2OZlJhA2B5D7OaZOdESXVcW89CGM32AVvRZZ1sErXLtC3iHswl3hM0S287RO8E
r65FgphoPSpASonX4p4nLE04+L4ZU0t45h4q3Akq0q0B1Qcto7IoI4AdOaoHEA5H
3Yg1n4U7AgMBAAECggEAEJO/VcusY8qeEzxbJZ31wdLLOVWyigqkjZaI1+CSVNz5
hk9vXSRRKCuqh4cdZaOxTKlUMVInIbjarz53W1svYcHeGG4Rfn0SiZVMqdu/6M2S
bEttimOTNyyPRLNjnQ7H5YIKYlGbD2E3eBNZUr0Hkj67hHx5vkMK5flm+yoTXhaj
QFYZo441P5b3+yDmFxnHeIKMDZtSG3GFStCc1FGNh+EA8+ZYEsZaVBkaDDVn9gUu
e5gDF54AZe7Tx/b02gTCgXqLR5p23SwacG4AZijispHqrG4fUjhNidR5OrwgR7So
+N8GbICzVwQUuqKDT2jhoHSAaGZX7T2GrD8BdG4vwQKBgQDxG8s8ahgGUpq+GmU3
Lfh+iSVB1nN7m8k3dHgklejZvKRjNzfVbC3OqNt825VO8snfS7+NLyM8w7YA5RpB
AYU1FhG06Uc0YKeyQjM+7WlQtW151StaGuUezrTKIATnHQu3CqARncusQ8B6gTLE
moc4dyAMFqrfW0Uam0L1GlCWZwKBgQDZevTagYF1F/Rawbm8TCCmy0tkT+Fac6Q7
gAo9zO+ssx1O4PXLNNrzzp5TXzWA6qr/nflHgiiBrKWZ7jENppqHs6g6qn96Mh7+
YADV2ikR3Eo5L57P9opxunH1baQnHT9wQRjoFctBHYrfjEEOWuvGFFZtnG8dIOlE
Sd5B2tfODQKBgQCbo4ZpBE9n3XDYYG+P1BQBkoRDYKyBUUntizh23XJHA5fWF/Hp
ygAz1BqDGbfjE6SuiNYozBHiCq/1Ge79oX6cixd5AdEeBXqa/lLYPybpm4QEzk9C
xfO7FFHt3AduLPi/+pLjbEnqdH3OVpIwCVRaZcOBKiy5K9CK4UiysX7t5wKBgF4j
KvmqNS9KPytJz+wBx+Bq/ydcrF9KzzwyIDzACL7oiTcriTl8l4oRVdcgzzgOXBZp
ew3I+V+oK8aFpBYUl69FxPwf8S4jo+bYB4SJ+l0QzdATHNtIDIVN/yYNX5DOyDb+
9pj/VgvJjeNWApMEKCqFgyPPIwmoxVAZ6Wr4H5HBAoGAJ5yOQ29c9+a7dyggUoHm
k++C75cbw1LYo63xHvSUHomiKNYw+9+aMQ6aygwmrFhKgo2wT0ReLZb6zlJdcPg4
uJrS40T48xQv2FjCByzw6NMJnouaLeCnefAqu8uqbb3u/A+WBaS0B4h432oPEe1u
jZgILGpX9p4Cf9TAc0vXQsA=
-----END PRIVATE KEY-----'''
client_email = "daily-weather-logger@weatherdiaries.iam.gserviceaccount.com"
client_id = "101033650663746117222"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/daily-weather-logger%40weatherdiaries.iam.gserviceaccount.com"
universe_domain = "googleapis.com"